// <auto-generated />
namespace AbyssRunSite.ApplicationContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class NewInitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewInitial));
        
        string IMigrationMetadata.Id
        {
            get { return "202004300314356_NewInitial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
